package com.hsms.mapper;

import com.hsms.model.BillDetial;
import com.hsms.model.BillDetialExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BillDetialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_detial
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    long countByExample(BillDetialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_detial
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    int deleteByExample(BillDetialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_detial
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_detial
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    int insert(BillDetial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_detial
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    int insertSelective(BillDetial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_detial
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    List<BillDetial> selectByExample(BillDetialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_detial
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    BillDetial selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_detial
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") BillDetial record, @Param("example") BillDetialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_detial
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    int updateByExample(@Param("record") BillDetial record, @Param("example") BillDetialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_detial
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    int updateByPrimaryKeySelective(BillDetial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_detial
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    int updateByPrimaryKey(BillDetial record);
}