package com.hsms.mapper;

import com.hsms.model.DbBackup;
import com.hsms.model.DbBackupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DbBackupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_backup
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    long countByExample(DbBackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_backup
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    int deleteByExample(DbBackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_backup
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_backup
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    int insert(DbBackup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_backup
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    int insertSelective(DbBackup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_backup
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    List<DbBackup> selectByExample(DbBackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_backup
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    DbBackup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_backup
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    int updateByExampleSelective(@Param("record") DbBackup record, @Param("example") DbBackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_backup
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    int updateByExample(@Param("record") DbBackup record, @Param("example") DbBackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_backup
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    int updateByPrimaryKeySelective(DbBackup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_backup
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    int updateByPrimaryKey(DbBackup record);
}