package com.hsms.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.hsms.model.ShoppingCar;
import com.hsms.model.ShoppingCarExample;

public interface ShoppingCarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    long countByExample(ShoppingCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    int deleteByExample(ShoppingCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    int insert(ShoppingCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    int insertSelective(ShoppingCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    List<ShoppingCar> selectByExample(ShoppingCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    ShoppingCar selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") ShoppingCar record, @Param("example") ShoppingCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    int updateByExample(@Param("record") ShoppingCar record, @Param("example") ShoppingCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    int updateByPrimaryKeySelective(ShoppingCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_car
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    int updateByPrimaryKey(ShoppingCar record);
}