package com.hsms.model;

public class BillDetial {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_detial.id
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_detial.bill_code
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    private String billCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_detial.goods_id
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_detial.goods_name
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_detial.purchase_price
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    private String purchasePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_detial.sale_branch_price
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    private String saleBranchPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_detial.sale_box_price
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    private String saleBoxPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_detial.branch_num
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    private String branchNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_detial.box_num
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    private String boxNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_detial.transaction
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    private String transaction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_detial.status
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_detial.updater
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_detial.update_time
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_detial.creater
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_detial.create_time
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_detial.id
     *
     * @return the value of bill_detial.id
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_detial.id
     *
     * @param id the value for bill_detial.id
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_detial.bill_code
     *
     * @return the value of bill_detial.bill_code
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    public String getBillCode() {
        return billCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_detial.bill_code
     *
     * @param billCode the value for bill_detial.bill_code
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    public void setBillCode(String billCode) {
        this.billCode = billCode == null ? null : billCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_detial.goods_id
     *
     * @return the value of bill_detial.goods_id
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_detial.goods_id
     *
     * @param goodsId the value for bill_detial.goods_id
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_detial.goods_name
     *
     * @return the value of bill_detial.goods_name
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_detial.goods_name
     *
     * @param goodsName the value for bill_detial.goods_name
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_detial.purchase_price
     *
     * @return the value of bill_detial.purchase_price
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    public String getPurchasePrice() {
        return purchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_detial.purchase_price
     *
     * @param purchasePrice the value for bill_detial.purchase_price
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    public void setPurchasePrice(String purchasePrice) {
        this.purchasePrice = purchasePrice == null ? null : purchasePrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_detial.sale_branch_price
     *
     * @return the value of bill_detial.sale_branch_price
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    public String getSaleBranchPrice() {
        return saleBranchPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_detial.sale_branch_price
     *
     * @param saleBranchPrice the value for bill_detial.sale_branch_price
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    public void setSaleBranchPrice(String saleBranchPrice) {
        this.saleBranchPrice = saleBranchPrice == null ? null : saleBranchPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_detial.sale_box_price
     *
     * @return the value of bill_detial.sale_box_price
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    public String getSaleBoxPrice() {
        return saleBoxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_detial.sale_box_price
     *
     * @param saleBoxPrice the value for bill_detial.sale_box_price
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    public void setSaleBoxPrice(String saleBoxPrice) {
        this.saleBoxPrice = saleBoxPrice == null ? null : saleBoxPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_detial.branch_num
     *
     * @return the value of bill_detial.branch_num
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    public String getBranchNum() {
        return branchNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_detial.branch_num
     *
     * @param branchNum the value for bill_detial.branch_num
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    public void setBranchNum(String branchNum) {
        this.branchNum = branchNum == null ? null : branchNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_detial.box_num
     *
     * @return the value of bill_detial.box_num
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    public String getBoxNum() {
        return boxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_detial.box_num
     *
     * @param boxNum the value for bill_detial.box_num
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    public void setBoxNum(String boxNum) {
        this.boxNum = boxNum == null ? null : boxNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_detial.transaction
     *
     * @return the value of bill_detial.transaction
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    public String getTransaction() {
        return transaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_detial.transaction
     *
     * @param transaction the value for bill_detial.transaction
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    public void setTransaction(String transaction) {
        this.transaction = transaction == null ? null : transaction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_detial.status
     *
     * @return the value of bill_detial.status
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_detial.status
     *
     * @param status the value for bill_detial.status
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_detial.updater
     *
     * @return the value of bill_detial.updater
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_detial.updater
     *
     * @param updater the value for bill_detial.updater
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_detial.update_time
     *
     * @return the value of bill_detial.update_time
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_detial.update_time
     *
     * @param updateTime the value for bill_detial.update_time
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_detial.creater
     *
     * @return the value of bill_detial.creater
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_detial.creater
     *
     * @param creater the value for bill_detial.creater
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_detial.create_time
     *
     * @return the value of bill_detial.create_time
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_detial.create_time
     *
     * @param createTime the value for bill_detial.create_time
     *
     * @mbg.generated Sat Nov 24 15:06:05 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }
}