package com.hsms.model;

public class Brand {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.id
     *
     * @mbg.generated Sat Nov 24 15:05:13 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.title
     *
     * @mbg.generated Sat Nov 24 15:05:13 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.status
     *
     * @mbg.generated Sat Nov 24 15:05:13 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.updater
     *
     * @mbg.generated Sat Nov 24 15:05:13 CST 2018
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.update_time
     *
     * @mbg.generated Sat Nov 24 15:05:13 CST 2018
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.creater
     *
     * @mbg.generated Sat Nov 24 15:05:13 CST 2018
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.create_time
     *
     * @mbg.generated Sat Nov 24 15:05:13 CST 2018
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.id
     *
     * @return the value of brand.id
     *
     * @mbg.generated Sat Nov 24 15:05:13 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.id
     *
     * @param id the value for brand.id
     *
     * @mbg.generated Sat Nov 24 15:05:13 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.title
     *
     * @return the value of brand.title
     *
     * @mbg.generated Sat Nov 24 15:05:13 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.title
     *
     * @param title the value for brand.title
     *
     * @mbg.generated Sat Nov 24 15:05:13 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.status
     *
     * @return the value of brand.status
     *
     * @mbg.generated Sat Nov 24 15:05:13 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.status
     *
     * @param status the value for brand.status
     *
     * @mbg.generated Sat Nov 24 15:05:13 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.updater
     *
     * @return the value of brand.updater
     *
     * @mbg.generated Sat Nov 24 15:05:13 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.updater
     *
     * @param updater the value for brand.updater
     *
     * @mbg.generated Sat Nov 24 15:05:13 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.update_time
     *
     * @return the value of brand.update_time
     *
     * @mbg.generated Sat Nov 24 15:05:13 CST 2018
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.update_time
     *
     * @param updateTime the value for brand.update_time
     *
     * @mbg.generated Sat Nov 24 15:05:13 CST 2018
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.creater
     *
     * @return the value of brand.creater
     *
     * @mbg.generated Sat Nov 24 15:05:13 CST 2018
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.creater
     *
     * @param creater the value for brand.creater
     *
     * @mbg.generated Sat Nov 24 15:05:13 CST 2018
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.create_time
     *
     * @return the value of brand.create_time
     *
     * @mbg.generated Sat Nov 24 15:05:13 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.create_time
     *
     * @param createTime the value for brand.create_time
     *
     * @mbg.generated Sat Nov 24 15:05:13 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }
}