package com.hsms.model;

public class DbBackup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_backup.id
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_backup.title
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_backup.comment
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_backup.backup_path
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    private String backupPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_backup.creater
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_backup.create_time
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_backup.restorer
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    private String restorer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_backup.restore_time
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    private String restoreTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_backup.id
     *
     * @return the value of db_backup.id
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_backup.id
     *
     * @param id the value for db_backup.id
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_backup.title
     *
     * @return the value of db_backup.title
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_backup.title
     *
     * @param title the value for db_backup.title
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_backup.comment
     *
     * @return the value of db_backup.comment
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_backup.comment
     *
     * @param comment the value for db_backup.comment
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_backup.backup_path
     *
     * @return the value of db_backup.backup_path
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    public String getBackupPath() {
        return backupPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_backup.backup_path
     *
     * @param backupPath the value for db_backup.backup_path
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    public void setBackupPath(String backupPath) {
        this.backupPath = backupPath == null ? null : backupPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_backup.creater
     *
     * @return the value of db_backup.creater
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_backup.creater
     *
     * @param creater the value for db_backup.creater
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_backup.create_time
     *
     * @return the value of db_backup.create_time
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_backup.create_time
     *
     * @param createTime the value for db_backup.create_time
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_backup.restorer
     *
     * @return the value of db_backup.restorer
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    public String getRestorer() {
        return restorer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_backup.restorer
     *
     * @param restorer the value for db_backup.restorer
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    public void setRestorer(String restorer) {
        this.restorer = restorer == null ? null : restorer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_backup.restore_time
     *
     * @return the value of db_backup.restore_time
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    public String getRestoreTime() {
        return restoreTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_backup.restore_time
     *
     * @param restoreTime the value for db_backup.restore_time
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    public void setRestoreTime(String restoreTime) {
        this.restoreTime = restoreTime == null ? null : restoreTime.trim();
    }
}