package com.hsms.model;

import java.util.ArrayList;
import java.util.List;

public class DbBackupExample extends BaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table db_backup
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table db_backup
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table db_backup
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_backup
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    public DbBackupExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_backup
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_backup
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_backup
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_backup
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_backup
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_backup
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_backup
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_backup
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_backup
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_backup
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table db_backup
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("comment is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("comment is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("comment =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("comment <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("comment >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("comment >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("comment <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("comment <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("comment like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("comment not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("comment in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("comment not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("comment between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("comment not between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andBackupPathIsNull() {
            addCriterion("backup_path is null");
            return (Criteria) this;
        }

        public Criteria andBackupPathIsNotNull() {
            addCriterion("backup_path is not null");
            return (Criteria) this;
        }

        public Criteria andBackupPathEqualTo(String value) {
            addCriterion("backup_path =", value, "backupPath");
            return (Criteria) this;
        }

        public Criteria andBackupPathNotEqualTo(String value) {
            addCriterion("backup_path <>", value, "backupPath");
            return (Criteria) this;
        }

        public Criteria andBackupPathGreaterThan(String value) {
            addCriterion("backup_path >", value, "backupPath");
            return (Criteria) this;
        }

        public Criteria andBackupPathGreaterThanOrEqualTo(String value) {
            addCriterion("backup_path >=", value, "backupPath");
            return (Criteria) this;
        }

        public Criteria andBackupPathLessThan(String value) {
            addCriterion("backup_path <", value, "backupPath");
            return (Criteria) this;
        }

        public Criteria andBackupPathLessThanOrEqualTo(String value) {
            addCriterion("backup_path <=", value, "backupPath");
            return (Criteria) this;
        }

        public Criteria andBackupPathLike(String value) {
            addCriterion("backup_path like", value, "backupPath");
            return (Criteria) this;
        }

        public Criteria andBackupPathNotLike(String value) {
            addCriterion("backup_path not like", value, "backupPath");
            return (Criteria) this;
        }

        public Criteria andBackupPathIn(List<String> values) {
            addCriterion("backup_path in", values, "backupPath");
            return (Criteria) this;
        }

        public Criteria andBackupPathNotIn(List<String> values) {
            addCriterion("backup_path not in", values, "backupPath");
            return (Criteria) this;
        }

        public Criteria andBackupPathBetween(String value1, String value2) {
            addCriterion("backup_path between", value1, value2, "backupPath");
            return (Criteria) this;
        }

        public Criteria andBackupPathNotBetween(String value1, String value2) {
            addCriterion("backup_path not between", value1, value2, "backupPath");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNull() {
            addCriterion("creater is null");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNotNull() {
            addCriterion("creater is not null");
            return (Criteria) this;
        }

        public Criteria andCreaterEqualTo(String value) {
            addCriterion("creater =", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotEqualTo(String value) {
            addCriterion("creater <>", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThan(String value) {
            addCriterion("creater >", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThanOrEqualTo(String value) {
            addCriterion("creater >=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThan(String value) {
            addCriterion("creater <", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThanOrEqualTo(String value) {
            addCriterion("creater <=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLike(String value) {
            addCriterion("creater like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotLike(String value) {
            addCriterion("creater not like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterIn(List<String> values) {
            addCriterion("creater in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotIn(List<String> values) {
            addCriterion("creater not in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterBetween(String value1, String value2) {
            addCriterion("creater between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotBetween(String value1, String value2) {
            addCriterion("creater not between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("create_time like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("create_time not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andRestorerIsNull() {
            addCriterion("restorer is null");
            return (Criteria) this;
        }

        public Criteria andRestorerIsNotNull() {
            addCriterion("restorer is not null");
            return (Criteria) this;
        }

        public Criteria andRestorerEqualTo(String value) {
            addCriterion("restorer =", value, "restorer");
            return (Criteria) this;
        }

        public Criteria andRestorerNotEqualTo(String value) {
            addCriterion("restorer <>", value, "restorer");
            return (Criteria) this;
        }

        public Criteria andRestorerGreaterThan(String value) {
            addCriterion("restorer >", value, "restorer");
            return (Criteria) this;
        }

        public Criteria andRestorerGreaterThanOrEqualTo(String value) {
            addCriterion("restorer >=", value, "restorer");
            return (Criteria) this;
        }

        public Criteria andRestorerLessThan(String value) {
            addCriterion("restorer <", value, "restorer");
            return (Criteria) this;
        }

        public Criteria andRestorerLessThanOrEqualTo(String value) {
            addCriterion("restorer <=", value, "restorer");
            return (Criteria) this;
        }

        public Criteria andRestorerLike(String value) {
            addCriterion("restorer like", value, "restorer");
            return (Criteria) this;
        }

        public Criteria andRestorerNotLike(String value) {
            addCriterion("restorer not like", value, "restorer");
            return (Criteria) this;
        }

        public Criteria andRestorerIn(List<String> values) {
            addCriterion("restorer in", values, "restorer");
            return (Criteria) this;
        }

        public Criteria andRestorerNotIn(List<String> values) {
            addCriterion("restorer not in", values, "restorer");
            return (Criteria) this;
        }

        public Criteria andRestorerBetween(String value1, String value2) {
            addCriterion("restorer between", value1, value2, "restorer");
            return (Criteria) this;
        }

        public Criteria andRestorerNotBetween(String value1, String value2) {
            addCriterion("restorer not between", value1, value2, "restorer");
            return (Criteria) this;
        }

        public Criteria andRestoreTimeIsNull() {
            addCriterion("restore_time is null");
            return (Criteria) this;
        }

        public Criteria andRestoreTimeIsNotNull() {
            addCriterion("restore_time is not null");
            return (Criteria) this;
        }

        public Criteria andRestoreTimeEqualTo(String value) {
            addCriterion("restore_time =", value, "restoreTime");
            return (Criteria) this;
        }

        public Criteria andRestoreTimeNotEqualTo(String value) {
            addCriterion("restore_time <>", value, "restoreTime");
            return (Criteria) this;
        }

        public Criteria andRestoreTimeGreaterThan(String value) {
            addCriterion("restore_time >", value, "restoreTime");
            return (Criteria) this;
        }

        public Criteria andRestoreTimeGreaterThanOrEqualTo(String value) {
            addCriterion("restore_time >=", value, "restoreTime");
            return (Criteria) this;
        }

        public Criteria andRestoreTimeLessThan(String value) {
            addCriterion("restore_time <", value, "restoreTime");
            return (Criteria) this;
        }

        public Criteria andRestoreTimeLessThanOrEqualTo(String value) {
            addCriterion("restore_time <=", value, "restoreTime");
            return (Criteria) this;
        }

        public Criteria andRestoreTimeLike(String value) {
            addCriterion("restore_time like", value, "restoreTime");
            return (Criteria) this;
        }

        public Criteria andRestoreTimeNotLike(String value) {
            addCriterion("restore_time not like", value, "restoreTime");
            return (Criteria) this;
        }

        public Criteria andRestoreTimeIn(List<String> values) {
            addCriterion("restore_time in", values, "restoreTime");
            return (Criteria) this;
        }

        public Criteria andRestoreTimeNotIn(List<String> values) {
            addCriterion("restore_time not in", values, "restoreTime");
            return (Criteria) this;
        }

        public Criteria andRestoreTimeBetween(String value1, String value2) {
            addCriterion("restore_time between", value1, value2, "restoreTime");
            return (Criteria) this;
        }

        public Criteria andRestoreTimeNotBetween(String value1, String value2) {
            addCriterion("restore_time not between", value1, value2, "restoreTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table db_backup
     *
     * @mbg.generated do_not_delete_during_merge Sun Dec 02 15:21:11 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table db_backup
     *
     * @mbg.generated Sun Dec 02 15:21:11 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}