package com.hsms.model;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.code
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.brand_id
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    private Integer brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.brand_title
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    private String brandTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.title
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.purchase_price
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    private String purchasePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.sale_branch_price
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    private String saleBranchPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.sale_box_price
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    private String saleBoxPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.specification
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    private String specification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.status
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.updater
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.update_time
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.creater
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.create_time
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.code
     *
     * @return the value of goods.code
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.code
     *
     * @param code the value for goods.code
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.brand_id
     *
     * @return the value of goods.brand_id
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.brand_id
     *
     * @param brandId the value for goods.brand_id
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.brand_title
     *
     * @return the value of goods.brand_title
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    public String getBrandTitle() {
        return brandTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.brand_title
     *
     * @param brandTitle the value for goods.brand_title
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    public void setBrandTitle(String brandTitle) {
        this.brandTitle = brandTitle == null ? null : brandTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.title
     *
     * @return the value of goods.title
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.title
     *
     * @param title the value for goods.title
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.purchase_price
     *
     * @return the value of goods.purchase_price
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    public String getPurchasePrice() {
        return purchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.purchase_price
     *
     * @param purchasePrice the value for goods.purchase_price
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    public void setPurchasePrice(String purchasePrice) {
        this.purchasePrice = purchasePrice == null ? null : purchasePrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.sale_branch_price
     *
     * @return the value of goods.sale_branch_price
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    public String getSaleBranchPrice() {
        return saleBranchPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.sale_branch_price
     *
     * @param saleBranchPrice the value for goods.sale_branch_price
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    public void setSaleBranchPrice(String saleBranchPrice) {
        this.saleBranchPrice = saleBranchPrice == null ? null : saleBranchPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.sale_box_price
     *
     * @return the value of goods.sale_box_price
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    public String getSaleBoxPrice() {
        return saleBoxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.sale_box_price
     *
     * @param saleBoxPrice the value for goods.sale_box_price
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    public void setSaleBoxPrice(String saleBoxPrice) {
        this.saleBoxPrice = saleBoxPrice == null ? null : saleBoxPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.specification
     *
     * @return the value of goods.specification
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    public String getSpecification() {
        return specification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.specification
     *
     * @param specification the value for goods.specification
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    public void setSpecification(String specification) {
        this.specification = specification == null ? null : specification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.status
     *
     * @return the value of goods.status
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.status
     *
     * @param status the value for goods.status
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.updater
     *
     * @return the value of goods.updater
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.updater
     *
     * @param updater the value for goods.updater
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.update_time
     *
     * @return the value of goods.update_time
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.update_time
     *
     * @param updateTime the value for goods.update_time
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.creater
     *
     * @return the value of goods.creater
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.creater
     *
     * @param creater the value for goods.creater
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.create_time
     *
     * @return the value of goods.create_time
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.create_time
     *
     * @param createTime the value for goods.create_time
     *
     * @mbg.generated Sat Nov 24 15:09:18 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }
}