package com.hsms.model;

public class Supplier {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.id
     *
     * @mbg.generated Sat Nov 24 15:16:53 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.name
     *
     * @mbg.generated Sat Nov 24 15:16:53 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.address
     *
     * @mbg.generated Sat Nov 24 15:16:53 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.phone
     *
     * @mbg.generated Sat Nov 24 15:16:53 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.status
     *
     * @mbg.generated Sat Nov 24 15:16:53 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.updater
     *
     * @mbg.generated Sat Nov 24 15:16:53 CST 2018
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.update_time
     *
     * @mbg.generated Sat Nov 24 15:16:53 CST 2018
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.creater
     *
     * @mbg.generated Sat Nov 24 15:16:53 CST 2018
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.create_time
     *
     * @mbg.generated Sat Nov 24 15:16:53 CST 2018
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.id
     *
     * @return the value of supplier.id
     *
     * @mbg.generated Sat Nov 24 15:16:53 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.id
     *
     * @param id the value for supplier.id
     *
     * @mbg.generated Sat Nov 24 15:16:53 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.name
     *
     * @return the value of supplier.name
     *
     * @mbg.generated Sat Nov 24 15:16:53 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.name
     *
     * @param name the value for supplier.name
     *
     * @mbg.generated Sat Nov 24 15:16:53 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.address
     *
     * @return the value of supplier.address
     *
     * @mbg.generated Sat Nov 24 15:16:53 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.address
     *
     * @param address the value for supplier.address
     *
     * @mbg.generated Sat Nov 24 15:16:53 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.phone
     *
     * @return the value of supplier.phone
     *
     * @mbg.generated Sat Nov 24 15:16:53 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.phone
     *
     * @param phone the value for supplier.phone
     *
     * @mbg.generated Sat Nov 24 15:16:53 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.status
     *
     * @return the value of supplier.status
     *
     * @mbg.generated Sat Nov 24 15:16:53 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.status
     *
     * @param status the value for supplier.status
     *
     * @mbg.generated Sat Nov 24 15:16:53 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.updater
     *
     * @return the value of supplier.updater
     *
     * @mbg.generated Sat Nov 24 15:16:53 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.updater
     *
     * @param updater the value for supplier.updater
     *
     * @mbg.generated Sat Nov 24 15:16:53 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.update_time
     *
     * @return the value of supplier.update_time
     *
     * @mbg.generated Sat Nov 24 15:16:53 CST 2018
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.update_time
     *
     * @param updateTime the value for supplier.update_time
     *
     * @mbg.generated Sat Nov 24 15:16:53 CST 2018
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.creater
     *
     * @return the value of supplier.creater
     *
     * @mbg.generated Sat Nov 24 15:16:53 CST 2018
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.creater
     *
     * @param creater the value for supplier.creater
     *
     * @mbg.generated Sat Nov 24 15:16:53 CST 2018
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.create_time
     *
     * @return the value of supplier.create_time
     *
     * @mbg.generated Sat Nov 24 15:16:53 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.create_time
     *
     * @param createTime the value for supplier.create_time
     *
     * @mbg.generated Sat Nov 24 15:16:53 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }
}